In [1]:
import librosa
import librosa.display
import matplotlib.pyplot as plt
import numpy as np
import scipy
from scipy import signal
from IPython.display import Audio



sa = librosa.load("test_data/speakerA.wav")[0]
sb = librosa.load("test_data/speakerB.wav")[0]

t = np.linspace(0, 5, len(sa))
sb = sb[0:len(sa)]
plt.subplot(311)
plt.plot(t, sa)
plt.title("Speaker A")
plt.subplot(312)
plt.plot(t, sb)
plt.title("Speaker B")
plt.subplot(313)
plt.plot(t, sa+sb)
plt.title("Speaker A+B")
plt.show()

fsa = librosa.stft(sa)
fsb = librosa.stft(sb)
fboth = librosa.stft(sa+sb)
plt.subplot(311)
librosa.display.specshow(librosa.amplitude_to_db(fsa, ref=np.max),y_axis='log', x_axis='time')
plt.title("Speaker A")
plt.subplot(312)
librosa.display.specshow(librosa.amplitude_to_db(fsb, ref=np.max),y_axis='log', x_axis='time')
plt.title("Speaker B")
plt.subplot(313)
librosa.display.specshow(librosa.amplitude_to_db(fboth, ref=np.max),y_axis='log', x_axis='time')
plt.title("Speaker A+B")
plt.show()

recover_b = fboth - fsa
recover_sb = librosa.istft(recover_b)
print(recover_sb, sb[0:len(sa)])


Audio(recover_sb, rate=22050)

<Figure size 640x480 with 3 Axes>

/home/hanqing/anaconda3/envs/DL/lib/python3.6/site-packages/librosa/core/spectrum.py:1029: UserWarning: amplitude_to_db was called on complex input so phase information will be discarded. To suppress this warning, call amplitude_to_db(np.abs(S)) instead.
  warnings.warn('amplitude_to_db was called on complex input so phase '


<Figure size 640x480 with 3 Axes>

[ 0.00546331 -0.00150412 -0.00806059 ...  0.06898835 -0.07217348
 -0.03784037] [ 0.00546331 -0.00150412 -0.00806059 ... -0.08316469  0.21387577
  0.        ]


In [2]:
Audio(sa+sb, rate=22050)

In [7]:
a = np.random.randn(4,2,3)
b = np.random.randn(4,2,3)

In [8]:
a, b

(array([[[-2.33920876, -1.048457  , -1.92116615],
         [ 1.64556712,  0.48606927, -0.26685497]],
 
        [[ 0.69906488, -0.02082094,  0.54750419],
         [-1.24552809, -1.20675852,  1.19840808]],
 
        [[ 0.01939983,  0.39234358,  1.38790424],
         [ 2.0879396 ,  1.1263414 ,  0.75123913]],
 
        [[ 1.04751725, -0.8803596 ,  0.65707382],
         [ 1.85166799,  0.31361458, -1.87777998]]]),
 array([[[ 0.25112729,  0.46401211,  1.17593544],
         [ 1.42602928, -1.60581233,  1.76559177]],
 
        [[-1.06946875,  0.5029787 , -0.93524917],
         [ 0.71738462, -0.53903423,  0.12006673]],
 
        [[ 0.43335893,  0.70579726, -0.96505082],
         [-0.24921548, -0.55228521,  2.37632042]],
 
        [[ 1.45322962,  1.23304426,  1.02834971],
         [-0.97759637,  2.0354021 ,  0.55298938]]]))

In [10]:
for ai, bi in zip(a,b):
    print (ai, bi)

[[-2.33920876 -1.048457   -1.92116615]
 [ 1.64556712  0.48606927 -0.26685497]] [[ 0.25112729  0.46401211  1.17593544]
 [ 1.42602928 -1.60581233  1.76559177]]
[[ 0.69906488 -0.02082094  0.54750419]
 [-1.24552809 -1.20675852  1.19840808]] [[-1.06946875  0.5029787  -0.93524917]
 [ 0.71738462 -0.53903423  0.12006673]]
[[0.01939983 0.39234358 1.38790424]
 [2.0879396  1.1263414  0.75123913]] [[ 0.43335893  0.70579726 -0.96505082]
 [-0.24921548 -0.55228521  2.37632042]]
[[ 1.04751725 -0.8803596   0.65707382]
 [ 1.85166799  0.31361458 -1.87777998]] [[ 1.45322962  1.23304426  1.02834971]
 [-0.97759637  2.0354021   0.55298938]]


In [13]:
k = np.stack(a, axis=0)

In [14]:
k.shape

(4, 2, 3)

In [17]:
l = list()
for ai in a:
    l.append(ai)
m = np.stack(l, axis=0)

In [18]:
m.shape

(4, 2, 3)

In [20]:
c = np.random.randn(3,2)
d = np.random.randn(3,2)
c,d

(array([[ 0.48176492,  0.22665315],
        [ 0.89325168,  1.05376147],
        [-0.61949672,  0.46889222]]), array([[ 0.48048595,  0.42595888],
        [-2.715747  , -0.84024807],
        [ 0.75451219, -0.98663781]]))

In [21]:
c+d

array([[ 0.96225087,  0.65261204],
       [-1.82249532,  0.2135134 ],
       [ 0.13501547, -0.5177456 ]])

In [22]:
f = c+d

In [23]:
f.shape

(3, 2)

In [24]:
f

array([[ 0.96225087,  0.65261204],
       [-1.82249532,  0.2135134 ],
       [ 0.13501547, -0.5177456 ]])

In [25]:
import torch

In [26]:
a = torch.Tensor(np.random.randn(3,2))

In [27]:
a

tensor([[-1.2821, -0.7141],
        [ 0.3372, -1.9221],
        [-1.5173, -0.4468]])

In [28]:
np.power(10, a*0.05)

tensor([[0.8628, 0.9211],
        [1.0396, 0.8015],
        [0.8397, 0.9499]])

In [29]:
y, sr = librosa.load(librosa.util.example_audio_file())

In [30]:
D = librosa.stft(y)

In [31]:
D.shape

(1025, 2647)

In [32]:
D

array([[ 2.4692644e-03+0.0000000e+00j,  4.3183967e-02+0.0000000e+00j,
         6.6134012e-01+0.0000000e+00j, ...,
        -1.0665493e-04+0.0000000e+00j, -2.9083538e-05+0.0000000e+00j,
         3.5335881e-05+0.0000000e+00j],
       [ 2.5613750e-03-2.3293406e-21j,  5.1407147e-02+5.1062149e-03j,
         3.1246996e-01+5.1239032e-01j, ...,
        -6.2639515e-07-1.7899574e-05j,  6.2111591e-05+8.9027693e-05j,
        -6.6326764e-05-2.4181933e-05j],
       [ 8.7682583e-04-1.5736723e-21j,  9.5419168e-02+4.4643220e-02j,
        -9.8567039e-02+4.2620054e-01j, ...,
         1.4601435e-04+8.8074259e-05j, -1.1195048e-04-1.7414341e-04j,
         1.2966398e-05+1.1292481e-04j],
       ...,
       [ 1.4228847e-07+2.0208397e-20j,  6.3397829e-07+1.9270085e-07j,
         3.4933978e-06+1.4349748e-05j, ...,
         2.7226141e-08-5.3577986e-09j,  5.0930309e-09+2.3720723e-08j,
        -9.9086683e-10-2.6649944e-09j],
       [-4.1231786e-08+1.2430209e-19j,  2.0072287e-07+8.4723195e-07j,
        -5.8938385e-06

In [33]:
D.real

array([[ 2.4692644e-03,  4.3183967e-02,  6.6134012e-01, ...,
        -1.0665493e-04, -2.9083538e-05,  3.5335881e-05],
       [ 2.5613750e-03,  5.1407147e-02,  3.1246996e-01, ...,
        -6.2639515e-07,  6.2111591e-05, -6.6326764e-05],
       [ 8.7682583e-04,  9.5419168e-02, -9.8567039e-02, ...,
         1.4601435e-04, -1.1195048e-04,  1.2966398e-05],
       ...,
       [ 1.4228847e-07,  6.3397829e-07,  3.4933978e-06, ...,
         2.7226141e-08,  5.0930309e-09, -9.9086683e-10],
       [-4.1231786e-08,  2.0072287e-07, -5.8938385e-06, ...,
         3.2704012e-08,  1.2779749e-08, -2.3387960e-09],
       [-1.9735630e-07, -9.5166081e-07, -1.2456289e-05, ...,
        -7.1973460e-08, -2.6135027e-08, -2.8467342e-09]], dtype=float32)

In [34]:
D.imag

array([[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [-2.3293406e-21,  5.1062149e-03,  5.1239032e-01, ...,
        -1.7899574e-05,  8.9027693e-05, -2.4181933e-05],
       [-1.5736723e-21,  4.4643220e-02,  4.2620054e-01, ...,
         8.8074259e-05, -1.7414341e-04,  1.1292481e-04],
       ...,
       [ 2.0208397e-20,  1.9270085e-07,  1.4349748e-05, ...,
        -5.3577986e-09,  2.3720723e-08, -2.6649944e-09],
       [ 1.2430209e-19,  8.4723195e-07,  9.2962337e-06, ...,
        -2.5333902e-08, -1.9941305e-08, -1.6290808e-09],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00]], dtype=float32)

In [37]:
c = np.stack((D.real, D.imag), axis=2)

In [38]:
c.shape

(1025, 2647, 2)

In [43]:
x = torch.randn(3, 3)
x

tensor([[ 0.2477,  0.1392,  0.4522],
        [-0.0025, -0.0269,  0.7426],
        [-1.4692,  0.5049, -0.3149]])

In [44]:
y = torch.transpose(x, 0 ,1)

In [45]:
y

tensor([[ 0.2477, -0.0025, -1.4692],
        [ 0.1392, -0.0269,  0.5049],
        [ 0.4522,  0.7426, -0.3149]])

In [46]:
a = torch.Tensor([1,2,3])
b = torch.exp(1j*a)

TypeError: mul(): argument 'other' (position 1) must be Tensor, not complex

In [48]:
mag = np.array([1,2,3])
phase = np.array([-3.14, 0, 3.13])
complexn = mag * np.exp(1j*phase)

In [49]:
complexn

array([-0.99999873-0.00159265j,  2.        +0.j        ,
       -2.99979842+0.03477718j])

In [54]:
tmag = torch.Tensor(mag)
tphase = torch.Tensor(phase)
treal = tmag * torch.cos(tphase)
timag = tmag * torch.sin(tphase)

In [55]:
treal

tensor([-1.0000,  2.0000, -2.9998])

In [56]:
timag

tensor([-0.0016,  0.0000,  0.0348])